# Generated by Django 3.0.5 on 2020-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0002_auto_20200418_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_pub',
            field=models.DateTimeField(blank=True, default='2020-04-18', null=True, verbose_name='Date'),
        ),
    ]
