# Generated by Django 3.0.5 on 2020-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0004_auto_20200418_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auth',
        ),
        migrations.AddField(
            model_name='author',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='hanabis_blog', to='hanabis_blog.Post', verbose_name='Posts'),
        ),
    ]
