# Generated by Django 3.0.5 on 2020-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0006_auto_20200418_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=5000, null=True, verbose_name='About me'),
        ),
    ]
