# Generated by Django 3.0.5 on 2020-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0007_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date_pub',
            field=models.CharField(blank=True, default='2020-04-19', max_length=50, null=True, verbose_name='Date'),
        ),
    ]
