# Generated by Django 3.0.5 on 2020-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0008_auto_20200419_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_birth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Date of birth'),
        ),
    ]
