# Generated by Django 3.0.5 on 2020-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0009_author_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.ManyToManyField(blank=True, related_name='posts', to='hanabis_blog.Author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date_pub',
            field=models.CharField(blank=True, default='2020-04-20', max_length=50, null=True, verbose_name='Date'),
        ),
    ]
