# Generated by Django 3.0.5 on 2020-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0012_auto_20200420_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='hanabis_blog.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='hanabis_blog.Tag', verbose_name='tags'),
        ),
    ]
