# Generated by Django 3.0.5 on 2020-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0013_auto_20200420_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date_pub',
            field=models.CharField(auto_created=True, blank=True, default='2020-04-21', max_length=50, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email'),
        ),
    ]
