# Generated by Django 3.0.5 on 2020-04-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0017_auto_20200425_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
