# Generated by Django 3.0.5 on 2020-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0018_auto_20200425_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='hanabis_blog.Category', verbose_name='Categories'),
        ),
    ]
