# Generated by Django 3.0.5 on 2020-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0020_auto_20200426_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
