# Generated by Django 3.0.5 on 2020-04-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('hanabis_blog', '0024_auto_20200426_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserSocial',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.SocialAccount')),
                ('extra', models.ManyToManyField(related_name='review', to='hanabis_blog.Reviews')),
            ],
            bases=('socialaccount.socialaccount',),
        ),
    ]
