# Generated by Django 3.0.5 on 2020-04-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('hanabis_blog', '0025_myusersocial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUserSocial',
        ),
    ]
