# Generated by Django 3.0.5 on 2020-04-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0031_auto_20200426_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='username',
        ),
    ]
