# Generated by Django 3.0.5 on 2020-04-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('hanabis_blog', '0033_auto_20200426_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='socialaccount.SocialAccount', verbose_name='Review'),
        ),
    ]
