# Generated by Django 3.0.5 on 2020-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('hanabis_blog', '0035_auto_20200426_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_pub',
            field=models.CharField(auto_created=True, blank=True, default='2020-04-27', max_length=50, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ManyToManyField(blank=True, default=models.CharField(max_length=100, null=True, verbose_name='username'), related_name='reviews', to='socialaccount.SocialAccount', verbose_name='User'),
        ),
    ]
