# Generated by Django 3.0.5 on 2020-04-27 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('hanabis_blog', '0044_auto_20200427_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileNew',
        ),
    ]
