# Generated by Django 3.0.5 on 2020-04-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0045_auto_20200427_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hanabis_blog.ProfileNew'),
        ),
    ]
