# Generated by Django 3.0.5 on 2020-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0046_auto_20200427_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='profile',
        ),
    ]
