# Generated by Django 3.0.5 on 2020-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabis_blog', '0048_remove_profilenew_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='profile',
        ),
        migrations.AddField(
            model_name='reviews',
            name='picture',
            field=models.URLField(blank=True, verbose_name='User Avatar'),
        ),
        migrations.DeleteModel(
            name='ProfileNew',
        ),
    ]
